include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    avoid_redundant_argument_values: true
    no_literal_bool_comparisons: true
    unnecessary_await_in_return: true
    prefer_final_locals: true
    use_decorated_box: true
  
analyzer:
  exclude:
    - lib/generated/**
  errors:
    prefer_relative_imports: warning
    constant_identifier_names: ignore