name: arch_todo
description: "To-do app example with a flutter proposed architecture"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  result_dart: ^2.0.0
  shared_preferences: ^2.5.1
  auto_injector: ^2.0.5
  routefly: ^3.1.2
  result_command: ^1.2.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
