// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: 'home', uri: Uri.parse('home'), routeBuilder: b0Builder),
  RouteEntity(
    key: 'create_to_do',
    uri: Uri.parse('create_to_do'),
    routeBuilder: b1Builder,
  ),
];

const routePaths = (path: '/', home: '/home', createToDo: '/create_to_do');
